### ISSUE TITLE
Allow to use a custom `EvaluationContext` as well as custom `.` property evaluation

### ISSUE THREAD

**Issue by sangupta** [google/escapevelocity#14]
Currently, the `Template` is tied to using `PlainEvaluationContext` even though there is an extensibility point available by implementing `EvaluationContext` interface. We may want to add a new method such as `public String evaluate(EvaluationContext context)` and `protected EvaluationContext buildContext(MethodFinder methodFinder)`.

Similarly, in method `MemberReferenceNode.evaluate()` there is only a way to check for `Map` access or `getProperty()` kind of accessors. However, it would be easier to extend this by adding a custom evaluator to say, read property via reflection or from a `JsonObject` or else. 

This shall allow clients to use the library without building `Context` as a pure `Map` with getters/setters. I currently modified it to make use of `JsonObject` from `Gson` library for my own needs. Happy to help and raise a PR.

Let me know your thoughts on the same.

**Comment by eamonnmcmanus** [comment]
Thanks, those are interesting ideas!

We've tried to keep the public API of EscapeVelocity very small (one public class, one public interface, two exceptions). While we could enlarge it as suggested, I'd be interested in seeing the use cases first. Did you run into this in a project?

An alternative would be to document how to use custom implementations of `Map` to achieve specialized behaviours. For example, evaluating `${foo}` ends up calling `vars.containsKey("foo")` and `vars.get("foo")`, where `vars` is the `Map` passed to the `evaluate` method. You can do dynamic things in those methods; you don't need to start with a static `Map` where everything is present at the start. Similarly, evaluating `${foo.bar}` calls the same two methods as before and then, if the result is also a `Map`, it will call `map.get("bar")`. So you can implement `Map` so it does reflection or JSON or whatever.

**Comment by sangupta** [comment]
I have been experimenting merge templates with arbitrary JSON data from RPC calls, including providing an intermediate layer that massages the response. I could theoretically convert the the response to a `Map` instance via `Gson` first, but that adds some overhead, as we are already working with `JsonObject` instances.

We could add a method (optionally one more) as:

```java
public void registerResolver(Class<?> objectClass, Resolver resolver) ;
public void removeResolver(Class<?> objectClass);
``` 
where `Resolver` interface that may be defined as:
```java
interface Resolver {

    Object resolve(Object entity, String attribute);

}
```

This adds a new interface called `Resolver` which we may even replace with Java interface [BiFunction](https://docs.oracle.com/javase/8/docs/api/java/util/function/BiFunction.html) such as:

```
public void registerResolver(Class<?> objectClass, BiFunction<Object, String, Object> resolver);
```

Usage would simplify to:
```java
registerResolver(JsonObject.class, new BiFunction() {
    @Override
    public Object apply(Object entity, String attribute) {
        return ((JsonObject) entity).getAsObject(attribute);
    }
});
```

This way we would not have added any new class/interface, yet provided an extensibility to the system.

**Comment by eamonnmcmanus** [comment]
Let me see if I understand. You'd like to give the `Template.evaluate` method a `Map`, call it `vars`, where some of the values in the map are instances of `JsonObject`. Let's say `vars.get("foo")` is `fooObject`. Then, when `fooObject` is a `JsonObject`, you'd like for `${foo.bar}` to call `fooObject.getAsObject("bar")`. Otherwise it should do whatever it would normally would do.

I think it is possible to do this with the existing API. You could wrap all your `JsonObject` variables in a `Wrapper` class, like this:

```java
    JsonObject fooObject = new JsonObject();
    fooObject.add("bar", new JsonObject());
    fooObject.add("baz", new JsonPrimitive("not an object"));
    Map<String, Object> vars1 = Map.of("foo", fooObject, "bar", 23);
    Map<String, Object> vars2 =
        Maps.transformValues(vars1,
            value -> value instanceof JsonObject jsonObject ? new Wrapper(jsonObject) : value);
    Template template = Template.parseFrom(new StringReader("$bar $foo.bar"));
    System.out.println(template.evaluate(vars2));
```

(This is [`Maps.transformValues`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/Maps.html#transformValues(java.util.Map,com.google.common.base.Function)) from Guava.)

The `Wrapper` class can look like this:

```java
  class Wrapper extends AbstractMap<String, JsonObject> {
    private final JsonObject wrapped;

    Wrapper(JsonObject wrapped) {
      this.wrapped = wrapped;
    }

    @Override
    public Set<Map.Entry<String, JsonObject>> entrySet() {
      return wrapped.entrySet().stream()
          .filter(e -> e.getValue() instanceof JsonObject)
          .map(e -> Map.entry(e.getKey(), (JsonObject) e.getValue())).collect(toSet());
    }

    @Override
    public JsonObject get(Object o) {
      // This method is implemented for efficiency; AbstractMap.get would work but be slower.
      if (o instanceof String key) {
        JsonElement element = wrapped.get(key);
        if (element instanceof JsonObject object) {
          return object;
        }
      }
      return null;
    }
  }
```

Then the `System.out.println` above will print this:

```
23 {}
```

where `{}` is `$foo.bar`, which has correctly evaluated the `fooObject.getAsObject("bar")`.

This is what I was talking about earlier when I said we could usefully document this technique.

Also, incidentally, I realized when looking into this that EscapeVelocity has a bug: if `$foo` is a `Map` and you write `$foo.bar`, and if the map doesn't actually have `"bar"` as a key, then it will render as `null` instead of producing an exception as Apache Velocity would. I'm going to work on fixing that.

**Comment by sangupta** [comment]
For the current use-case at hand, the above technique shall work. But this destructs the original `JsonObject` - thus, requiring a deep-clone before working with it.  One would need to deep-traverse the `Map` and and wrap all possible objects before using them directly. This becomes expensive if the objects are being generated in a 3rd party framework where you have no control on objects (Json, Xml, Database entities etc).

In my thoughts it would be simpler to use a resolver functionality. This way the client can register for all possible object types, and then work with values without altering them in any way.
